<?php
/**
 * Package: Toristy Booking.
 * Author: Toristy<support@toristy.com>.
 */

namespace Toristy\Cores\Admins;


use Toristy\Cores\Settings;
use Toristy\Helpers\Domain;

class TabPage extends AdminTab
{
    public function __construct(Settings $settings, string $key)
    {
        $this->Title = 'Page Options';
        parent::__construct($settings, 'toristy_pages', [], 'page', $key);
    }

    public function Group($inputs)
    {
        foreach ($inputs as $input => $value) {
            if (is_array($value)) {
                $inputs[$input] = $this->Group($value);
            } elseif (strpos(strtolower($input), 'color') !== false && $inputs[$input][0] === "#") {
                $inputs[$input] = ltrim($value, "#");
            }
        }
        return $inputs;
    }

    public function Load($args)
    {
        $name = $args["name"];
        $default = $args["default"];
        $value = (isset($this->Options[$name]) && $this->Options[$name] !== "") ? $this->Options[$name] : $default;
        if (strpos($name, 'color') !== false) {
            echo '<input type="text" name="'.$this->Option.'['.$name.']" value="#'.$value.'" class="toristy-color" data-default-color="#'.$default.'" />';
        } else if ($name === "home-image") {
            $preview = (strlen($value) > 0) ? $value : Domain::Url('assets/images/preview.png');
            echo '<img id="toristy-preview" src="'.$preview.'"/>';
            echo '<input type="hidden" id="toristy-image" name="'.$this->Option.'['.$name.']" value="'.$value.'" />';
            echo "<input id='toristy-button' type='button' class='button-primary' value='Upload' />";
        } else if (strpos($name, 'info') !== false) {
            //echo '<textarea name="'.$this->Option.'['.$name.']" class="toristy-info">'.$value.'</textarea>';
            $size = $args["size"];
            $limit = $args["limit"];
            if (strpos($limit, '30') !== false) {
                echo '<textarea class="toristy-text" name="'.$this->Option.'['.$name.']" class="toristy-info">'.$value.'</textarea>';
            } else {
                echo '<input class="toristy-input" name="'.$this->Option.'['.$name.']" type="text" value="'.$value.'" />';
            }
            echo "<p>$limit</p>";
        }
    }

    public function Section(string $title = '')
    {
        if ($title === 'General') {
            echo '<p>General settings all pages generated by this plugin.</p>';
        } elseif ($title === 'Home Page') {
            echo '<p>Home page setting only options.</p>';
        } elseif ($title === 'Filter Page') {
            echo '<p>Filter page setting only options.</p>';
        }
    }

    protected function Populate()
    {
        $this->Add('color', 'Highlight, Border, Button Color', [
            "default" => "245076",
            "name" => "color"
        ], 'General');

        $this->Add('home-image', 'Home Page Search Image', [
            "default" => "",
            "name" => "home-image"
        ], 'Home Page');

        $this->Add('info-home', 'Home Page Search Text', [
            "default" => "",
            "name" => "info-home",
            "size" => 30,
            "limit" => 'Limit of 10 words'
        ], 'Home Page');

        $this->Add('info-filter', 'Filter Page Search Text', [
            "default" => "",
            "name" => "info-filter",
            "size" => 15,
            "limit" => 'Limit of 2 words'
        ], 'Filter Page');

        $this->Add('bg-color', 'Information Background Color', [
            "default" => "245076",
            "name" => "bg-color"
        ], 'Home Page');

        $this->Add('txt-color', 'Information Text Color', [
            "default" => "ffffff",
            "name" => "txt-color"
        ], 'Home Page');

        $this->Add('info-title-1', 'Information Note Title 1', [
            "default" => "",
            "name" => "info-title-1",
            "size" => 30,
            "limit" => 'Limit of 10 words'
        ], 'Home Page');

        $this->Add('info-1', 'Information Note 1', [
            "default" => "",
            "name" => "info-1",
            "size" => 50,
            "limit" => 'Limit of 30 words'
        ], 'Home Page');

        $this->Add('info-title-2', 'Information Note Title 2', [
            "default" => "",
            "name" => "info-title-2",
            "size" => 30,
            "limit" => 'Limit of 10 words'
        ], 'Home Page');

        $this->Add('info-2', 'Information Note 2', [
            "default" => "",
            "name" => "info-2",
            "size" => 50,
            "limit" => 'Limit of 30 words'
        ], 'Home Page');
    }
}